# Generated by Django 5.2.10 on 2026-01-14 10:25

import django.db.models.deletion
import therapy_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to=therapy_sessions.models.SessionAudio.session_audio_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionAudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_key', models.CharField(max_length=1024)),
                ('upload_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='uploading', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('treatment_plan', models.JSONField(blank=True, default=list)),
                ('therapist_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'session_report',
            },
        ),
        migrations.CreateModel(
            name='SessionTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_transcript', models.TextField(blank=True)),
                ('cleaned_transcript', models.TextField(blank=True)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=30)),
            ],
            options={
                'db_table': 'session_transcript',
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('uploaded', 'Uploaded'), ('recorded', 'Recorded'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='empty', max_length=30)),
                ('last_error_stage', models.CharField(blank=True, default='', max_length=30)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('notes_before', models.TextField(blank=True)),
                ('notes_after', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'therapy_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
