# Generated by Django 6.0 on 2025-12-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField(blank=True)),
                ('cleaned_transcript', models.TextField(blank=True)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='therapy_sessions.therapysession')),
            ],
            options={
                'db_table': 'session_transcript',
            },
        ),
    ]
