# Generated by Django 6.0 on 2025-12-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_sessiontranscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_summary', models.TextField(blank=True)),
                ('key_points', models.TextField(blank=True)),
                ('risk_flags', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('therapist_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='therapy_sessions.therapysession')),
            ],
            options={
                'db_table': 'session_report',
            },
        ),
    ]
