# Generated by Django 6.0 on 2026-01-02 16:23

import django.db.models.deletion
import therapy_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0005_rename_uploaded_at_sessionaudio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionaudio',
            name='audio_file',
            field=models.FileField(upload_to=therapy_sessions.models.SessionAudio.session_audio_path),
        ),
        migrations.CreateModel(
            name='SessionAudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_key', models.CharField(max_length=1024)),
                ('upload_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='uploading', max_length=32)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_upload', to='therapy_sessions.therapysession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
