# Generated by Django 5.2.9 on 2026-01-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0006_alter_sessionaudio_audio_file_sessionaudioupload'),
        ('therapy_sessions', '0006_alter_therapysession_options'),
    ]

    operations = [
    ]
