# Generated by Django 6.0 on 2025-12-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_patient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='therapistprofile',
            table='therapist_profile',
        ),
    ]
